name: Generate snake game

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - uses: Sutil/snk@master
        with:
          github_user_name: ByancaMatos01
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'purple'

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
